title: Mariella Arias
logo: /assets/images/profile-photo.jpg
description: >
  Software Developer with a passion for building intuitive web applications. I thrive on transforming complex requirements into clean, maintainable code and creating seamless user experiences. Currently focused on web development and always eager to learn new technologies.  
  <br> ğŸ“© <a href="mailto:arias.mariella1@gmail.com">Email Me</a> â€¢ ğŸŒ <a href="https://www.linkedin.com/in/mariella-arias/">LinkedIn</a>

theme: jekyll-theme-minimal

show_downloads: false  
